/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package book.shop;

import java.awt.Color;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author ASUS
 */
public class Admin_Login extends javax.swing.JFrame {

    

    /** Creates new form Admin_Login */
    public Admin_Login() {
        initComponents();
        jPanel2.setBackground(new Color(255,255,255,180));
        
        // center the form
   // this.setLocationRelativeTo(null);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        Admin_Log = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Admin_Password = new javax.swing.JPasswordField();
        Admin_Name = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1000, 500));
        setUndecorated(true);
        setResizable(false);
        setSize(new java.awt.Dimension(1000, 500));
        getContentPane().setLayout(null);

        jPanel1.setMaximumSize(new java.awt.Dimension(1000, 500));
        jPanel1.setLayout(null);

        jPanel2.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Login to the System");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(0, 30, 700, 30);

        Admin_Log.setBackground(new java.awt.Color(228, 192, 245));
        Admin_Log.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Admin_Log.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/done1.png"))); // NOI18N
        Admin_Log.setText("Login");
        Admin_Log.setBorder(null);
        Admin_Log.setBorderPainted(false);
        Admin_Log.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Admin_Log.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Admin_LogMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Admin_LogMouseExited(evt);
            }
        });
        Admin_Log.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Admin_LogActionPerformed(evt);
            }
        });
        jPanel2.add(Admin_Log);
        Admin_Log.setBounds(450, 240, 140, 50);

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_user_shield_52px.png"))); // NOI18N
        jPanel2.add(jLabel5);
        jLabel5.setBounds(30, 80, 150, 150);

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Admin Name");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(200, 110, 130, 30);

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Password");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(200, 170, 130, 30);

        Admin_Password.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Admin_Password.setText("Password");
        Admin_Password.setBorder(null);
        Admin_Password.setOpaque(false);
        Admin_Password.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                Admin_PasswordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                Admin_PasswordFocusLost(evt);
            }
        });
        jPanel2.add(Admin_Password);
        Admin_Password.setBounds(350, 170, 240, 30);

        Admin_Name.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Admin_Name.setText("Admin_Name");
        Admin_Name.setBorder(null);
        Admin_Name.setOpaque(false);
        Admin_Name.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                Admin_NameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                Admin_NameFocusLost(evt);
            }
        });
        Admin_Name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Admin_NameActionPerformed(evt);
            }
        });
        jPanel2.add(Admin_Name);
        Admin_Name.setBounds(350, 110, 240, 30);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(290, 90, 700, 330);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("ABC Book Shop (PVT) LTD");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(290, 30, 700, 50);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("M19980307007");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(0, 230, 290, 50);

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/30.gif"))); // NOI18N
        jPanel1.add(jLabel9);
        jLabel9.setBounds(0, 330, 290, 130);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("M.KASUN VIMUKTHI PERERA");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(0, 170, 290, 50);

        jLabel6.setBackground(new java.awt.Color(0, 0, 0));
        jLabel6.setOpaque(true);
        jPanel1.add(jLabel6);
        jLabel6.setBounds(0, 0, 290, 500);

        jLabel1.setBackground(new java.awt.Color(102, 0, 153));
        jLabel1.setOpaque(true);
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 1000, 500);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1000, 500);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void Admin_NameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Admin_NameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Admin_NameActionPerformed

    private void Admin_LogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Admin_LogActionPerformed
        // TODO add your handling code here:
        PreparedStatement st;
        ResultSet rs;
        
        String Username =  Admin_Name.getText();
        String Password = String.valueOf(Admin_Password.getPassword());
        
        String query = "SELECT * FROM `admin` WHERE `Name` = ? AND `Password` = ?";
        
        if(Username.trim().equals("username"))
        {
            JOptionPane.showMessageDialog(null, "Enter Your Admin_name", "Empty Admin_name", 2);
        }
        else
            
        if(Password.trim().equals("Password"))
        { 
            JOptionPane.showMessageDialog(null, "Enter Your Password", "Empty Password", 2);
        }       
        else
        {
        try {
            st = BookDB.getConnection().prepareStatement(query);
            
            st.setString(1, Username);
            st.setString(2, Password);
            rs = st.executeQuery();
            
            if(rs.next())
            {
                
                Home form = new Home();
                form.setVisible(true);
                form.pack();
                form.setLocationRelativeTo(null);
                this.dispose();
                
             //   Home.Home_Admin_Name.setText(Admin_Login.Admin_Name.getText());
                
                
            }else{
                JOptionPane.showMessageDialog(null, "Invalid Admin_name / Password", "Login Error", 2);
                
                
                
            }
        } catch (SQLException ex) {
            Logger.getLogger(Admin_Login.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        }                                         

    }//GEN-LAST:event_Admin_LogActionPerformed

    private void Admin_NameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Admin_NameFocusGained
        // TODO add your handling code here:
        if(Admin_Name.getText().trim().toLowerCase().equals("admin_name"))
        {
            Admin_Name.setText("");
            Admin_Name.setForeground(Color.black);
            
        }
    }//GEN-LAST:event_Admin_NameFocusGained

    private void Admin_NameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Admin_NameFocusLost
        // TODO add your handling code here:
         if(Admin_Name.getText().trim().equals("") ||
           Admin_Name.getText().trim().toLowerCase().equals("admin_name"))
        {
            Admin_Name.setText("admin_name");
            Admin_Name.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_Admin_NameFocusLost

    private void Admin_PasswordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Admin_PasswordFocusGained
        // TODO add your handling code here:
        String pass = String.valueOf(Admin_Password.getPassword());
        
  
        if(pass.trim().toLowerCase().equals("password"))
        {
            Admin_Password.setText("");
            Admin_Password.setForeground(Color.black);
            
        }
    }//GEN-LAST:event_Admin_PasswordFocusGained

    private void Admin_PasswordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Admin_PasswordFocusLost
        // TODO add your handling code here:
        String pass = String.valueOf(Admin_Password.getPassword());
        
        if(pass.trim().equals("") ||
           pass.trim().toLowerCase().equals("password"))
        {
            Admin_Password.setText("password");
            Admin_Password.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_Admin_PasswordFocusLost

    private void Admin_LogMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Admin_LogMouseEntered
        // TODO add your handling code here:
         Admin_Log.setBackground(new Color(102,0,153));
    }//GEN-LAST:event_Admin_LogMouseEntered

    private void Admin_LogMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Admin_LogMouseExited
        // TODO add your handling code here:
        Admin_Log.setBackground(new Color(228,192,245));
    }//GEN-LAST:event_Admin_LogMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Admin_Login().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Admin_Log;
    public static javax.swing.JTextField Admin_Name;
    private javax.swing.JPasswordField Admin_Password;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables

}
